### ISSUE TITLE
Incorrect Parsing of Link Destination in Escaped Pointy Brackets

### ISSUE THREAD

**Issue by mjordan56** [dart-lang/markdown#326]
The markdown package incorrectly parses link destinations enclosed in escaped pointy brackets.

Both the [CommonMark](https://spec.commonmark.org/0.29/#example-490) and [GitHub Flavored Markdown](https://github.github.com/gfm/#example-502) specifications note that "_Pointy brackets that enclose links must be unescaped_"  (click on the document links to go to the examples in the specifications). The example from both specs show the example Markdown input data:

```
[link](<foo\>)
 ```
should produce the following HTML output:
```
<p>[link](&lt;foo&gt;)</p>
```
However, the markdown package does not properly parse this link. The following sample code:
```
import 'package:markdown/markdown.dart';

void main() {
  print(markdownToHtml('[link](<foo\>)'));
}
```
Produces the following incorrect HTML output:
```
<p><a href="foo">link</a></p>
```

**Comment by srawlins** [comment]
This is fixed at head. Not sure if it is a recent fix...

**Comment by mjordan56** [comment]
@srawlins I just tested this fix against the current version of the markdown package, version 4.0.0-nullsafety.0, and the issue has not been fixed. I still get the incorrect output stated. Could you please reverify that this problem has been fixed and that the output generated is in accordance with the GFM specification?
